<a href="https://colab.research.google.com/github/jweir136/Predicting-Percentages-Using-Indicators/blob/master/PredictingPercentWithIndicators.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split, cross_val_score, learning_curve
from sklearn.preprocessing import StandardScaler

!pip install stockstats

from stockstats import StockDataFrame as Sdf

Collecting stockstats
  Downloading https://files.pythonhosted.org/packages/59/34/77ef5a9c2573e59fa8fba8122cc160ffb0d86ad47493de6a313f05cfe9b2/stockstats-0.2.0-py2.py3-none-any.whl
Requirement already satisfied: numpy>=1.9.2 in /usr/local/lib/python3.6/dist-packages (from stockstats) (1.14.6)
Requirement already satisfied: pandas>=0.18.1 in /usr/local/lib/python3.6/dist-packages (from stockstats) (0.22.0)
Collecting int-date>=0.1.7 (from stockstats)
  Downloading https://files.pythonhosted.org/packages/43/27/31803df15173ab341fe7548c14154b54227dfd8f630daa09a1c6e7db52f7/int_date-0.1.8-py2.py3-none-any.whl
Requirement already satisfied: python-dateutil>=2 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.18.1->stockstats) (2.5.3)
Requirement already satisfied: pytz>=2011k in /usr/local/lib/python3.6/dist-packages (from pandas>=0.18.1->stockstats) (2018.7)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.6/dist-packages (from int-date>=0.1.7->stockstats) (1.11.0)
Installing collected packages: int-date, stockstats
Successfully installed int-date-0.1.8 stockstats-0.2.0

In [4]:
FB = pd.read_csv("FB.csv")
FB.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2012-05-18,42.049999,45.000000,38.000000,38.230000,38.230000,573576400
1,2012-05-21,36.529999,36.660000,33.000000,34.029999,34.029999,168192700
2,2012-05-22,32.610001,33.590000,30.940001,31.000000,31.000000,101786600
3,2012-05-23,31.370001,32.500000,31.360001,32.000000,32.000000,73600000
4,2012-05-24,32.950001,33.209999,31.770000,33.029999,33.029999,50237200

In [0]:
FB_stock = Sdf.retype(FB)

In [0]:
FB['sma'] = FB_stock['close_10_sma']
FB['boll'] = FB_stock['boll']

In [0]:
FB['percent'] = ((FB['adj close'] - FB['adj close'].shift(10)) / FB['adj close'].shift(10)) * 100

In [31]:
FB

,open,high,low,close,adj close,volume,close_10_sma,sma,close_20_sma,close_20_mstd,boll,boll_ub,boll_lb,percent
date,,,,,,,,,,,,,,
2012-05-18,42.049999,45.000000,38.000000,38.230000,38.230000,573576400,38.230000,38.230000,38.230000,NaN,38.230000,NaN,NaN,NaN
2012-05-21,36.529999,36.660000,33.000000,34.029999,34.029999,168192700,36.129999,36.129999,36.129999,2.969849,36.129999,42.069698,30.190301,NaN
2012-05-22,32.610001,33.590000,30.940001,31.000000,31.000000,101786600,34.420000,34.420000,34.420000,3.630744,34.420000,41.681487,27.158512,NaN
2012-05-23,31.370001,32.500000,31.360001,32.000000,32.000000,73600000,33.815000,33.815000,33.815000,3.201921,33.815000,40.218842,27.411157,NaN
2012-05-24,32.950001,33.209999,31.770000,33.029999,33.029999,50237200,33.658000,33.658000,33.658000,2.795080,33.658000,39.248159,28.067840,NaN
2012-05-25,32.900002,32.950001,31.110001,31.910000,31.910000,37149800,33.366666,33.366666,33.366666,2.599851,33.366666,38.566369,28.166964,NaN
2012-05-29,31.480000,31.690001,28.650000,28.840000,28.840000,78063400,32.720000,32.720000,32.720000,2.925736,32.720000,38.571472,26.868527,NaN
2012-05-30,28.700001,29.549999,27.860001,28.190001,28.190001,57267900,32.153750,32.153750,32.153750,3.146776,32.153750,38.447301,25.860199,NaN
2012-05-31,28.549999,29.670000,26.830000,29.600000,29.600000,111639200,31.870000,31.870000,31.870000,3.064155,31.870000,37.998311,25.741689,NaN
2012-06-01,28.889999,29.150000,27.389999,27.719999,27.719999,41855500,31.455000,31.455000,31.455000,3.173022,31.455000,37.801045,25.108955,NaN
2012-06-04,27.200001,27.650000,26.440001,26.900000,26.900000,35230300,30.322000,30.322000,31.040909,3.308693,31.040909,37.658295,24.423523,-29.636411
2012-06-05,26.700001,27.760000,25.750000,25.870001,25.870001,42473400,29.506000,29.506000,30.610000,3.490045,30.610000,37.590091,23.629909,-23.978837
2012-06-06,26.070000,27.170000,25.520000,26.809999,26.809999,61489200,29.087000,29.087000,30.317692,3.503734,30.317692,37.325160,23.310224,-13.516132
2012-06-07,27.000000,27.350000,26.150000,26.309999,26.309999,26159500,28.518000,28.518000,30.031428,3.532575,30.031428,37.096579,22.966277,-17.781253
2012-06-08,26.549999,27.760000,26.440001,27.100000,27.100000,38034000,27.925000,27.925000,29.836000,3.487207,29.836000,36.810413,22.861586,-17.953373
2012-06-11,27.180000,28.070000,26.840000,27.010000,27.010000,28219600,27.435000,27.435000,29.659375,3.442244,29.659375,36.543863,22.774886,-15.355688
2012-06-12,27.480000,27.770000,26.959999,27.400000,27.400000,15816800,27.291000,27.291000,29.526470,3.377686,29.526470,36.281842,22.771099,-4.993065
2012-06-13,27.660000,28.100000,27.100000,27.270000,27.270000,17102800,27.199000,27.199000,29.401111,3.319718,29.401111,36.040547,22.761675,-3.263572
2012-06-14,27.650000,28.320000,27.379999,28.290001,28.290001,16855000,27.068000,27.068000,29.342631,3.236241,29.342631,35.815113,22.870150,-4.425672
2012-06-15,28.510000,30.100000,28.350000,30.010000,30.010000,43563800,27.297000,27.297000,29.376000,3.153458,29.376000,35.682916,23.069084,8.261187
2012-06-18,29.959999,32.080002,29.410000,31.410000,31.410000,42978900,27.748000,27.748000,29.035000,2.431806,29.035000,33.898611,24.171389,16.765799
2012-06-19,31.540001,32.180000,30.700001,31.910000,31.910000,30849000,28.352000,28.352000,28.929000,2.241367,28.929000,33.411733,24.446266,23.347502
2012-06-20,31.920000,31.930000,31.150000,31.600000,31.600000,15553600,28.831000,28.831000,28.959000,2.274319,28.959000,33.507637,24.410363,17.866472
2012-06-21,31.670000,32.500000,31.510000,31.840000,31.840000,21875300,29.384000,29.384000,28.951000,2.263314,28.951000,33.477627,24.424373,21.018629
2012-06-22,32.410000,33.450001,32.060001,33.049999,33.049999,74834000,29.979000,29.979000,28.952000,2.265214,28.952000,33.482428,24.421571,21.955716
2012-06-25,32.860001,33.020000,31.549999,32.060001,32.060001,24352900,30.484000,30.484000,28.959500,2.275747,28.959500,33.510995,24.408005,18.696783
2012-06-26,32.689999,33.439999,32.500000,33.099998,33.099998,24858700,31.054000,31.054000,29.172500,2.456180,29.172500,34.084859,24.260140,20.802912
2012-06-27,32.459999,32.900002,31.900000,32.230000,32.230000,28568000,31.550000,31.550000,29.374500,2.535957,29.374500,34.446414,24.302586,18.188486
2012-06-28,31.959999,32.189999,30.900000,31.360001,31.360001,17713300,31.857000,31.857000,29.462500,2.574439,29.462500,34.611378,24.313622,10.851891
2012-06-29,31.920000,31.990000,30.760000,31.100000,31.100000,19526900,31.966000,31.966000,29.631500,2.564955,29.631500,34.761409,24.501591,3.632123
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-11-15,142.330002,144.839996,140.830002,143.850006,143.850006,30320300,146.511002,146.511002,148.127000,4.278165,148.127000,156.683331,139.570669,-5.205927
2018-11-16,141.070007,141.770004,137.770004,139.529999,139.529999,37250600,145.429001,145.429001,147.400999,4.448750,147.400999,156.298500,138.503499,-7.196546
2018-11-19,137.610001,137.750000,131.210007,131.550003,131.550003,44362700,143.716002,143.716002,146.239500,5.359983,146.239500,156.959467,135.519533,-11.521382
2018-11-20,127.029999,134.160004,126.849998,132.429993,132.429993,41939500,141.965001,141.965001,145.141499,5.831037,145.141499,156.803573,133.479426,-11.678010
2018-11-21,134.399994,137.190002,134.130005,134.820007,134.820007,25469700,140.294002,140.294002,144.580500,6.263723,144.580500,157.107946,132.053054,-11.027514
2018-11-23,133.649994,134.500000,131.259995,131.729996,131.729996,11886100,138.680002,138.680002,143.619500,6.694636,143.619500,157.008772,130.230228,-10.914993
2018-11-26,133.000000,137.000000,132.779999,136.380005,136.380005,24263600,137.822002,137.822002,143.170000,6.870417,143.170000,156.910834,129.429167,-5.918875
2018-11-27,135.750000,136.610001,133.710007,135.000000,135.000000,20750300,137.167001,137.167001,142.815501,7.107887,142.815501,157.031274,128.599728,-4.627342
2018-11-28,136.279999,136.789993,131.850006,136.759995,136.759995,29847500,136.627001,136.627001,142.342500,7.183764,142.342500,156.710029,127.974972,-3.798543
2018-11-29,135.919998,139.990005,135.660004,138.679993,138.679993,24238700,136.073000,136.073000,141.687000,6.867498,141.687000,155.421997,127.952004,-3.841359
2018-11-30,138.259995,140.970001,137.360001,140.610001,140.610001,25732600,135.748999,135.748999,141.130000,6.447273,141.130000,154.024545,128.235455,-2.252350
2018-12-03,143.000000,143.679993,140.759995,141.089996,141.089996,24819200,135.904999,135.904999,140.667000,6.071872,140.667000,152.810743,128.523257,1.118037
2018-12-04,140.729996,143.389999,137.160004,137.929993,137.929993,30307400,136.542998,136.542998,140.129500,5.794688,140.129500,151.718877,128.540123,4.849859
2018-12-06,133.820007,139.699997,133.669998,139.630005,139.630005,28218100,137.262999,137.262999,139.614000,5.314719,139.614000,150.243439,128.984561,5.436844
2018-12-07,139.250000,140.869995,136.660004,137.419998,137.419998,21195500,137.522998,137.522998,138.908500,4.527964,138.908500,147.964427,129.852573,1.928490
2018-12-10,139.600006,143.050003,139.009995,141.850006,141.850006,26422200,138.534999,138.534999,138.607501,4.078691,138.607501,146.764882,130.450119,7.682388
2018-12-11,143.880005,143.880005,141.100006,142.080002,142.080002,20300300,139.104999,139.104999,138.463500,3.889039,138.463500,146.241579,130.685422,4.179496
2018-12-12,143.080002,147.190002,142.509995,144.500000,144.500000,23696900,140.054999,140.054999,138.611000,4.064257,138.611000,146.739515,130.482485,7.037037
2018-12-13,145.570007,145.850006,143.190002,145.009995,145.009995,18148600,140.879999,140.879999,138.753500,4.241345,138.753500,147.236190,130.270809,6.032466
2018-12-14,143.339996,146.009995,142.509995,144.059998,144.059998,21785800,141.417999,141.417999,138.745500,4.230629,138.745500,147.206757,130.284242,3.879438
2018-12-17,143.080002,144.919998,138.419998,140.190002,140.190002,24334000,141.376000,141.376000,138.562499,4.074484,138.562499,146.711468,130.413531,-0.298698
2018-12-18,141.080002,145.929993,139.830002,143.660004,143.660004,24709100,141.633000,141.633000,138.769000,4.227869,138.769000,147.224738,130.313262,1.821538
2018-12-19,141.210007,144.910004,132.500000,133.240005,133.240005,57404900,141.164002,141.164002,138.853500,4.090655,138.853500,147.034810,130.672190,-3.400267
2018-12-20,130.699997,135.570007,130.000000,133.399994,133.399994,40297900,140.541000,140.541000,138.902000,4.015548,138.902000,146.933097,130.870903,-4.461800
2018-12-21,133.389999,134.899994,123.419998,124.949997,124.949997,56901500,139.294000,139.294000,138.408499,5.023591,138.408499,148.455681,128.361318,-9.074371
2018-12-24,123.099998,129.740005,123.019997,124.059998,124.059998,22066000,137.515000,137.515000,138.024999,5.793955,138.024999,149.612910,126.437089,-12.541422
2018-12-26,126.000000,134.240005,125.889999,134.179993,134.179993,39723400,136.724999,136.724999,137.914999,5.847467,137.914999,149.609933,126.220065,-5.560254
2018-12-27,132.440002,134.990005,129.669998,134.520004,134.520004,31202500,135.726999,135.726999,137.890999,5.861030,137.890999,149.613059,126.168939,-6.906572
2018-12-28,135.339996,135.919998,132.199997,133.199997,133.199997,22627600,134.545999,134.545999,137.712999,5.950561,137.712999,149.614122,125.811876,-8.144265
2018-12-31,134.449997,134.639999,129.949997,131.089996,131.089996,24567200,133.248999,133.248999,137.333499,6.125113,137.333499,149.583725,125.083274,-9.003195

In [0]:
X = FB[['sma', 'boll']].shift(10).dropna()
y = FB['percent'].dropna()

trainX, testX, trainY, testY = train_test_split(X.values, y.values, test_size=.2)

In [0]:
lr = Pipeline([
    ("scaler", StandardScaler()),
    ("lr", LinearRegression())
])

In [20]:
score = cross_val_score(lr, trainX, trainY, cv=10, verbose=3, n_jobs=-1, scoring='neg_mean_squared_error')

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  10 out of  10 | elapsed:    0.0s finished

In [23]:
np.sqrt(-score.mean()) / FB['adj close'].mean()

0.07413399391088148

In [33]:
lr.fit(trainX, trainY)

lr.predict([[141.376000, 138.562499	]])

array([0.51429689])